version: "3.1"

services:
    php:
        container_name: lendmn_sdk_php
        build: docker/php
        restart: on-failure
        user: "1000"
        volumes:
            - ./docker/php/docker.ini:/usr/local/etc/php/conf.d/docker.ini
            - .:/var/local/lendmn_sdk
